```vim
set nocompatible
let $LANG='en'
set lm=en

set encoding=utf-8
set columns=180
set lines=45
set go=
set go+=m
set cursorline
set cursorcolumn
syn on
syntax enable

set ruler
set showcmd
"set wildmenu
"set backspace=indent,eol,start
"set history=20

"set laststatus=2
set number
set relativenumber
filetype on
"filetype plugin on              "载入文件类型插件
set shiftwidth=4
set softtabstop=4
"set et               "编辑时把所有制表符替换为空格
set autoindent
set ts=4
set expandtab
"set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<,space:·
"set listchars=eol:$,tab:>-
set listchars=tab:>-
set list

set undodir=~/.vim/.swap/
set backupdir=~/.vim/.swap/
set directory=~/.vim/.swap/

set hlsearch
set smartcase
set incsearch
"colorscheme default

"++++++++++++++++++++++折叠+++++++++++++++++++++++++
" These may cause lag on ubuntu.
"set foldmethod=syntax           "设置语法折叠
"set foldcolumn=0                 "设置折叠区域宽度
"set foldenable                "开启折叠
"set foldlevel=100               "设置折叠层数 
"set guifont=DejaVu_Sans_Mono:h9

"set shell=D:\bash\
"set shell=\"C:\Program\ Files\Git\bin\bash.exe\"\

au FileType c,cpp,h,hpp,C,CPP,H,HPP,Hpp,Cpp,java map <F12> :%!astyle --mode=c --style=google -n -s4pk1W1xWw<CR> 

set t_Co=256
call plug#begin('~/.vim/.plug')
Plug 'scrooloose/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'altercation/vim-colors-solarized'
"Plug 'scrooloose/syntastic'
Plug 'ludovicchabant/vim-gutentags'
call plug#end()

" gutentags 搜索工程目录的标志，碰到这些文件/目录名就停止向上一级目录递归
let g:gutentags_project_root = ['.root', '.svn', '.git', '.hg', '.project']

" 所生成的数据文件的名称
let g:gutentags_ctags_tagfile = '.tags'

" 将自动生成的 tags 文件全部放入 ~/.cache/tags 目录中，避免污染工程目录
let s:vim_tags = expand('~/.vim/.ctags/vim-gutentags/tags')
let g:gutentags_cache_dir = s:vim_tags

" 配置 ctags 的参数
let g:gutentags_ctags_extra_args = ['--fields=+niazS', '--extra=+q']
let g:gutentags_ctags_extra_args += ['--c++-kinds=+px']
let g:gutentags_ctags_extra_args += ['--c-kinds=+px']

" 检测 ~/.cache/tags 不存在就新建
if !isdirectory(s:vim_tags)
   silent! call mkdir(s:vim_tags, 'p')
endif

map <F2> :silent! NERDTreeToggle<CR>
let NERDTreeWinPos="left"   "将窗口显示在右边
let g:NERDTreeDirArrows = 1
let g:NERDTreeDirArrowExpandable = '+'
let g:NERDTreeDirArrowCollapsible = '-'
let g:NERDTreeDirArrowCollapsible = '-'

" ctrlp usage -> http://ctrlpvim.github.io/ctrlp.vim/#installation
let g:ctrlp_max_files=0
let g:ctrlp_max_depth=40
let g:ctrlp_use_caching=1
let g:ctrlp_working_path_mode = "ra"
let g:ctrlp_match_window_bottom=1
let g:ctrlp_max_height=15
let g:ctrlp_match_window_reversed=0
let g:ctrlp_mruf_max=500
let g:ctrlp_follow_symlinks=1
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v[\/]\.(git|hg|svn|rvm)$',
    \ 'file': '\v\.(exe|so|dll|zip|tar|tar.gz|pyc)$',
    \ }


let g:airline_powerline_fonts = 0
if !exists('g:airline_symbols')
    let g:airline_symbols={}
endif
let g:airline_theme='cool'

colorscheme default
set background=light
```

```vim
set nocompatible
let $LANG='en'
set lm=en

set encoding=utf-8
set columns=180
set lines=45
set go=
set go+=m
set cursorline
set cursorcolumn
syn on
syntax enable

set ruler
set showcmd
"set wildmenu
"set backspace=indent,eol,start
"set history=20

"set laststatus=2
set number
set relativenumber
filetype on
"filetype plugin on              "ÔØÈëÎÄ¼þÀàÐÍ²å¼þ
set shiftwidth=4
set softtabstop=4
"set et               "±à¼­Ê±°ÑËùÓÐÖÆ±í·ûÌæ»»Îª¿Õ¸ñ
set autoindent
set ts=4
set expandtab
"set listchars=eol:?,tab:>¡¤,trail:~,extends:>,precedes:<,space:¡¤
"set listchars=eol:$,tab:>-
set listchars=tab:>-
set list

set undodir=~/.vim/.swap/
set backupdir=~/.vim/.swap/
set directory=~/.vim/.swap/

set hlsearch
set smartcase
set incsearch
"colorscheme default

"++++++++++++++++++++++ÕÛµþ+++++++++++++++++++++++++
" These may cause lag on ubuntu.
"set foldmethod=syntax           "ÉèÖÃÓï·¨ÕÛµþ
"set foldcolumn=0                 "ÉèÖÃÕÛµþÇøÓò¿í¶È
"set foldenable                "¿ªÆôÕÛµþ
"set foldlevel=100               "ÉèÖÃÕÛµþ²ãÊý 
"set guifont=DejaVu_Sans_Mono:h9

"set shell=D:\bash\
"set shell=\"C:\Program\ Files\Git\bin\bash.exe\"\

"au FileType c,cpp,h,hpp,C,CPP,H,HPP,Hpp,Cpp,java map <F12> :%!astyle --mode=c --style=google -n -s4pk1W1xWw<CR> 

set t_Co=256
call plug#begin('~/.vim/.plug')
"Plug 'scrooloose/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
"Plug 'octol/vim-cpp-enhanced-highlight'
"Plug 'altercation/vim-colors-solarized'
"Plug 'scrooloose/syntastic'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
"Plug 'valloric/youcompleteme'
Plug 'prabirshrestha/async.vim'
"Plug 'prabirshrestha/vim-lsp'
Plug 'autozimu/LanguageClient-neovim', {'branch': 'next'}
Plug 'rhysd/vim-clang-format'
" Use release branch (recommend)
"Plug 'neoclide/coc.nvim', {'branch': 'release'}
"Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}

call plug#end()

let g:clang_format#style_options = {
            \ "AccessModifierOffset" : -4,
            \ "AllowShortIfStatementsOnASingleLine" : "true",
            \ "AlwaysBreakTemplateDeclarations" : "true",
            \ "Standard" : "C++11"}

" map to <Leader>cf in C++ code
autocmd FileType c,cpp,objc nnoremap <buffer><Leader>cf :<C-u>ClangFormat<CR>
autocmd FileType c,cpp,objc vnoremap <buffer><Leader>cf :ClangFormat<CR>
" if you install vim-operator-user
autocmd FileType c,cpp,objc map <buffer><Leader>x <Plug>(operator-clang-format)
" Toggle auto formatting:
nmap <Leader>C :ClangFormatAutoToggle<CR>

let g:LanguageClient_loadSettings = 1
let g:LanguageClient_diagnosticsEnable = 0
let g:LanguageClient_settingsPath = expand('~/.vim/languageclient.json')
let g:LanguageClient_selectionUI = 'quickfix'
let g:LanguageClient_diagnosticsList = v:null
"let g:LanguageClient_hoverPreview = 'Never'
let g:LanguageClient_serverCommands = {}
let g:LanguageClient_serverCommands.c = ['clangd']
let g:LanguageClient_serverCommands.cpp = ['clangd']

noremap <leader>rd :call LanguageClient#textDocument_definition()<cr>
noremap <leader>rr :call LanguageClient#textDocument_references()<cr>
noremap <leader>rv :call LanguageClient#textDocument_hover()<cr>

" fzf key binding
nmap <C-p> :Files<CR>
nmap <C-e> :Buffers<CR>

let g:lsp_signs_enabled = 1         " enable signs
let g:lsp_diagnostics_echo_cursor = 1 " enable echo under cursor when in normal mode
let g:lsp_highlights_enabled = 0
let g:lsp_textprop_enabled = 0
let g:lsp_highlight_references_enabled = 1

map <F2> :silent! NERDTreeToggle<CR>
let NERDTreeWinPos="left"   "½«´°¿ÚÏÔÊ¾ÔÚÓÒ±ß
let g:NERDTreeDirArrows = 1
let g:NERDTreeDirArrowExpandable = '+'
let g:NERDTreeDirArrowCollapsible = '-'
let g:NERDTreeDirArrowCollapsible = '-'

if executable('clangd')
    augroup lsp_clangd
        autocmd!
        autocmd User lsp_setup call lsp#register_server({
                    \ 'name': 'clangd',
                    \ 'cmd': {server_info->['clangd']},
                    \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
                    \ })
        autocmd FileType c setlocal omnifunc=lsp#complete
        autocmd FileType cpp setlocal omnifunc=lsp#complete
        autocmd FileType objc setlocal omnifunc=lsp#complete
        autocmd FileType objcpp setlocal omnifunc=lsp#complete
    augroup end
endif



let g:airline_powerline_fonts = 0
if !exists('g:airline_symbols')
    let g:airline_symbols={}
endif
let g:airline_theme='cool'

colorscheme default
set background=light

```

```vim
set nocompatible
let $LANG='en'
set lm=en

set autoread
set encoding=utf-8
"set columns=180
"set lines=45
set go=
set go+=m
set cursorline
"set cursorcolumn
syn on
syntax enable

set ruler
set showcmd
"set wildmenu
"set backspace=indent,eol,start
"set history=20
set hidden

"set laststatus=2
set number
set relativenumber
filetype on
"filetype plugin on              "ÔØÈëÎÄ¼þÀàÐÍ²å¼þ
set shiftwidth=2
set softtabstop=2
"set et               "±à¼­Ê±°ÑËùÓÐÖÆ±í·ûÌæ»»Îª¿Õ¸ñ
set autoindent
set ts=2
set expandtab
"set listchars=eol:?,tab:>¡¤,trail:~,extends:>,precedes:<,space:¡¤
"set listchars=eol:$,tab:>-
set listchars=tab:>-
set list

set undodir=~/.config/nvim/.swap/
set backupdir=~/.config/nvim/.swap/
set directory=~/.config/nvim/.swap/

set hlsearch
set smartcase
set incsearch

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
if has("patch-8.1.1564")
  " Recently vim can merge signcolumn and number column into one
  set signcolumn=number
else
  set signcolumn=yes
endif

"++++++++++++++++++++++ÕÛµþ+++++++++++++++++++++++++
" These may cause lag on ubuntu.
"set foldmethod=syntax           "ÉèÖÃÓï·¨ÕÛµþ
"set foldcolumn=0                 "ÉèÖÃÕÛµþÇøÓò¿í¶È
"set foldenable                "¿ªÆôÕÛµþ
"set foldlevel=100               "ÉèÖÃÕÛµþ²ãÊý 
"set guifont=DejaVu_Sans_Mono:h9

"set shell=D:\bash\
"set shell=\"C:\Program\ Files\Git\bin\bash.exe\"\

"au FileType c,cpp,h,hpp,C,CPP,H,HPP,Hpp,Cpp,java map <F12> :%!astyle --mode=c --style=google -n -s4pk1W1xWw<CR> 

set t_Co=256
set ttimeoutlen=50

"===================================================================================================
call plug#begin('~/.config/nvim/.plug')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'rhysd/vim-clang-format'
"Plug 'autozimu/LanguageClient-neovim', {'branch': 'next','do': 'bash install.sh'}
"Plug 'prabirshrestha/vim-lsp'
"Plug 'mattn/vim-lsp-settings'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'tpope/vim-fugitive'
Plug 'sainnhe/sonokai'
"Plug 'altercation/vim-colors-solarized'
Plug 'nlknguyen/papercolor-theme'
call plug#end()

"===================================================================================================
" clang-format
let g:clang_format#style_options = {
      \ "AccessModifierOffset" : -2,
      \ "AllowShortIfStatementsOnASingleLine" : "true",
      \ "AlwaysBreakTemplateDeclarations" : "true",
      \ "Standard" : "C++11"}
"autocmd FileType c,cpp,objc nnoremap <buffer><Leader>cf :<C-u>ClangFormat<CR>
"autocmd FileType c,cpp,objc vnoremap <buffer><Leader>cf :ClangFormat<CR>
"autocmd FileType c,cpp,objc map <buffer><Leader>x <Plug>(operator-clang-format)
"nmap <Leader>C :ClangFormatAutoToggle<CR>
"nnoremap <silent> == :ClangFormat<CR>

"
"===================================================================================================
" coc-nvim
" GoTo code navigation.
nmap <silent> <C-]> <Plug>(coc-definition)
"nmap <silent> gd <Plug>(coc-definition)
"nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> <C-[> <Plug>(coc-implementation)
nmap <silent> <space>r <Plug>(coc-references)
nmap <silent> <A-o> :CocCommand clangd.switchSourceHeader<CR>
" Use K to show documentation in preview window.
nmap <silent> K :call <SID>show_documentation()<CR>
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction
" Formatting selected code.
"xmap <leader>f <Plug>(coc-format-selected)
"nmap <leader>f <Plug>(coc-format-selected)
" Mappings for CoCList
" Show all diagnostics.
nnoremap <silent><nowait> <space>a  :<C-u>CocList diagnostics<cr>
" Manage extensions.
"nnoremap <silent><nowait> <space>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
"nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
"nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
"nnoremap <silent><nowait> <space>p  :<C-u>CocListResume<CR>
nnoremap <nowait> <C-f> :CocSearch 


"
"===================================================================================================
" fugitive
nnoremap <nowait> <space>g :G 


"===================================================================================================
" language-client-neovim
"set runtimepath+=~/.vim/.plug/LanguageClient-neovim
"let g:LanguageClient_loadSettings = 1
"let g:LanguageClient_diagnosticsEnable = 1
"let g:LanguageClient_settingsPath = expand('~/.vim/languageclient.json')
"let g:LanguageClient_selectionUI = 'quickfix'
"let g:LanguageClient_diagnosticsList = v:null
""let g:LanguageClient_hoverPreview = 'Never'
"let g:LanguageClient_serverCommands = {
"    \ 'cpp': ['/usr/bin/clangd'],
"    \ 'c': ['/usr/bin/clangd'],
"    \ }
"
"nnoremap <silent> K :<Plug>(lcn-hover)<CR>
"nnoremap <silent> gd :<Plug>(lcn-definition)<CR>
"nnoremap <silent> <F2> :<Plug>(lcn-rename)<CR>
"
"
"===================================================================================================
" fzf key binding
nmap <C-p> :Files<CR>
nmap <C-e> :Buffers<CR>


"===================================================================================================
" vim-lsp
"let g:lsp_diagnostics_echo_cursor = 1 " enable echo under cursor when in normal mode
"let g:lsp_highlights_enabled = 1
"let g:lsp_textprop_enabled = 1
"let g:lsp_highlight_references_enabled = 1
"let g:lsp_signs_enabled = 1         " enable signs
"let g:lsp_signs_error = {'text': '✗'}
"
"if executable('clangd')
"    augroup lsp_clangd
"        autocmd!
"        autocmd User lsp_setup call lsp#register_server({
"                    \ 'name': 'clangd',
"                    \ 'cmd': {server_info->['clangd']},
"                    \ 'allowlist': ['c', 'cpp', 'objc', 'objcpp','cc'],
"                    \ })
"        autocmd FileType c setlocal omnifunc=lsp#complete
"        autocmd FileType cpp setlocal omnifunc=lsp#complete
"        autocmd FileType objc setlocal omnifunc=lsp#complete
"        autocmd FileType objcpp setlocal omnifunc=lsp#complete
"    augroup end
"endif
"
"
"===================================================================================================
" airline
let g:airline_theme='papercolor'
"let g:airline_statusline_ontop = 1

let g:airline_powerline_fonts = 0
if !exists('g:airline_symbols')
  let g:airline_symbols={}
endif
" powerline symbols
"let g:airline_left_sep = ''
"let g:airline_left_alt_sep = ''
"let g:airline_right_sep = ''
"let g:airline_right_alt_sep = ''
"let g:airline_symbols.branch = ''
"let g:airline_symbols.readonly = ''
"let g:airline_symbols.linenr = '☰'
"let g:airline_symbols.maxlinenr = ''
"let g:airline_symbols.dirty='⚡'
"
" unicode symbols
"let g:airline_left_sep = '»'
"let g:airline_left_sep = '▶'
"let g:airline_right_sep = '«'
"let g:airline_right_sep = '◀'
let g:airline_symbols.crypt = '🔒'
let g:airline_symbols.readonly = '🔒'
"let g:airline_symbols.linenr = '☰'
"let g:airline_symbols.linenr = '␊'
"let g:airline_symbols.linenr = '␤'
"let g:airline_symbols.linenr = '¶'
"let g:airline_symbols.maxlinenr = ''
"let g:airline_symbols.maxlinenr = '㏑'
let g:airline_symbols.branch = '⎇'
"let g:airline_symbols.paste = 'ρ'
"let g:airline_symbols.paste = 'Þ'
"let g:airline_symbols.paste = '∥'
"let g:airline_symbols.spell = 'Ꞩ'
"let g:airline_symbols.notexists = 'Ɇ'
let g:airline_symbols.whitespace = 'Ξ'


"
"===================================================================================================
" color scheme
colorscheme PaperColor
set background=light

```

```vim
set nocompatible
let $LANG='en'
set lm=en

set autoread
set encoding=utf-8
"set columns=180
"set lines=45
set go=
set go+=m
set cursorline
"set cursorcolumn
syn on
syntax enable

set ruler
set showcmd
"set wildmenu
"set backspace=indent,eol,start
"set history=20
set hidden

"set laststatus=2
set number
set relativenumber
filetype on
"filetype plugin on
set shiftwidth=2
set softtabstop=2
"set et
set autoindent
set ts=2
set expandtab
"set listchars=eol:?,tab:>
"set listchars=eol:$,tab:>
set listchars=tab:>-
set list

set undodir=~/.config/nvim/.swap/
set backupdir=~/.config/nvim/.swap/
set directory=~/.config/nvim/.swap/

set hlsearch
set smartcase
set incsearch
set t_Co=256
set ttimeoutlen=50

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
if has("patch-8.1.1564")
  " Recently vim can merge signcolumn and number column into one
  set signcolumn=number
else
  set signcolumn=yes
endif

"===================================================================================================
call plug#begin('~/.config/nvim/.plug')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'rhysd/vim-clang-format'
"Plug 'autozimu/LanguageClient-neovim', {'branch': 'next','do': 'bash install.sh'}
"Plug 'prabirshrestha/vim-lsp'
"Plug 'mattn/vim-lsp-settings'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'tpope/vim-fugitive'
Plug 'sainnhe/sonokai'
Plug 'altercation/vim-colors-solarized'
Plug 'nlknguyen/papercolor-theme'
call plug#end()

"===================================================================================================
" clang-format
let g:clang_format#style_options = {
      \ "AccessModifierOffset" : -2,
      \ "AllowShortIfStatementsOnASingleLine" : "true",
      \ "AlwaysBreakTemplateDeclarations" : "true",
      \ "Standard" : "C++11"}
"autocmd FileType c,cpp,objc nnoremap <buffer><Leader>cf :<C-u>ClangFormat<CR>
"autocmd FileType c,cpp,objc vnoremap <buffer><Leader>cf :ClangFormat<CR>
"autocmd FileType c,cpp,objc map <buffer><Leader>x <Plug>(operator-clang-format)
"nmap <Leader>C :ClangFormatAutoToggle<CR>
"nnoremap <silent> == :ClangFormat<CR>

"
"===================================================================================================
" coc-nvim
" GoTo code navigation.
nmap <silent> <C-]> <Plug>(coc-definition)
"nmap <silent> gd <Plug>(coc-definition)
"nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> <C-[> <Plug>(coc-implementation)
nmap <silent> <space>r <Plug>(coc-references)
nmap <silent> <A-o> :CocCommand clangd.switchSourceHeader<CR>
" Use K to show documentation in preview window.
nmap <silent> K :call <SID>show_documentation()<CR>
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction
" Formatting selected code.
"xmap <leader>f <Plug>(coc-format-selected)
"nmap <leader>f <Plug>(coc-format-selected)
" Mappings for CoCList
" Show all diagnostics.
nnoremap <silent><nowait> <space>a  :<C-u>CocLst diagnostics<cr>
" Manage extensions.
"nnoremap <silent><nowait> <space>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
"nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
"nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
"nnoremap <silent><nowait> <space>p  :<C-u>CocListResume<CR>
nnoremap <nowait> <C-f> :CocSearch 


"
"===================================================================================================
" fugitive
nnoremap <nowait> <space>g :G 


"===================================================================================================
" language-client-neovim
"set runtimepath+=~/.vim/.plug/LanguageClient-neovim
"let g:LanguageClient_loadSettings = 1
"let g:LanguageClient_diagnosticsEnable = 1
"let g:LanguageClient_settingsPath = expand('~/.vim/languageclient.json')
"let g:LanguageClient_selectionUI = 'quickfix'
"let g:LanguageClient_diagnosticsList = v:null
""let g:LanguageClient_hoverPreview = 'Never'
"let g:LanguageClient_serverCommands = {
"    \ 'cpp': ['/usr/bin/clangd'],
"    \ 'c': ['/usr/bin/clangd'],
"    \ }
"
"nnoremap <silent> K :<Plug>(lcn-hover)<CR>
"nnoremap <silent> gd :<Plug>(lcn-definition)<CR>
"nnoremap <silent> <F2> :<Plug>(lcn-rename)<CR>
"
"
"===================================================================================================
" fzf key binding
nmap <C-p> :Files<CR>
nmap <C-e> :Buffers<CR>
nmap <C-h> :History<CR>
nmap <A-w> :Windows<CR>
" This is the default option:
"   - Preview window on the right with 50% width
"   - CTRL-/ will toggle preview window.
" - Note that this array is passed as arguments to fzf#vim#with_preview function.
" - To learn more about preview window options, see `--preview-window` section of `man fzf`.
"let g:fzf_preview_window = ['right:50%', 'ctrl-/']

" Preview window on the upper side of the window with 40% height,
" hidden by default, ctrl-/ to toggle
"let g:fzf_preview_window = ['up:40%:hidden', 'ctrl-/']
"
" This is the default option:
"   - Preview window on the right with 50% width
"   - CTRL-/ will toggle preview window.
" - Note that this array is passed as arguments to fzf#vim#with_preview function.
" - To learn more about preview window options, see `--preview-window` section of `man fzf`.
"let g:fzf_preview_window = ['right:50%', 'ctrl-/']
" Preview window on the upper side of the window with 40% height,
" hidden by default, ctrl-/ to toggle
let g:fzf_preview_window = ['up:40%:hidden', 'ctrl-/']
" Empty value to disable preview window altogether
"let g:fzf_preview_window = []
"
" - down / up / left / right
let g:fzf_layout = { 'down': '40%' }
"
" Customize fzf colors to match your color scheme
" - fzf#wrap translates this to a set of `--color` options
let g:fzf_colors =
      \ { 'fg':      ['fg', 'Normal'],
      \ 'bg':      ['bg', 'Normal'],
      \ 'hl':      ['fg', 'Comment'],
      \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
      \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
      \ 'hl+':     ['fg', 'Statement'],
      \ 'info':    ['fg', 'PreProc'],
      \ 'border':  ['fg', 'Ignore'],
      \ 'prompt':  ['fg', 'Conditional'],
      \ 'pointer': ['fg', 'Exception'],
      \ 'marker':  ['fg', 'Keyword'],
      \ 'spinner': ['fg', 'Label'],
      \ 'header':  ['fg', 'Comment'] }
"
" Enable per-command history
" - History files will be stored in the specified directory
" - When set, CTRL-N and CTRL-P will be bound to 'next-history' and
"   'previous-history' instead of 'down' and 'up'.
let g:fzf_history_dir = '~/.local/share/fzf-history'


"===================================================================================================
" vim-lsp
"let g:lsp_diagnostics_echo_cursor = 1 " enable echo under cursor when in normal mode
"let g:lsp_highlights_enabled = 1
"let g:lsp_textprop_enabled = 1
"let g:lsp_highlight_references_enabled = 1
"let g:lsp_signs_enabled = 1         " enable signs
"let g:lsp_signs_error = {'text': '✗'}
"
"if executable('clangd')
"    augroup lsp_clangd
"        autocmd!
"        autocmd User lsp_setup call lsp#register_server({
"                    \ 'name': 'clangd',
"                    \ 'cmd': {server_info->['clangd']},
"                    \ 'allowlist': ['c', 'cpp', 'objc', 'objcpp','cc'],
"                    \ })
"        autocmd FileType c setlocal omnifunc=lsp#complete
"        autocmd FileType cpp setlocal omnifunc=lsp#complete
"        autocmd FileType objc setlocal omnifunc=lsp#complete
"        autocmd FileType objcpp setlocal omnifunc=lsp#complete
"    augroup end
"endif
"
"
"===================================================================================================
" airline
let g:airline_theme='papercolor'
let g:airline_statusline_ontop = 0

let g:airline_powerline_fonts = 0
if !exists('g:airline_symbols')
  let g:airline_symbols={}
endif
" powerline symbols
"let g:airline_left_sep = ''
"let g:airline_left_alt_sep = ''
"let g:airline_right_sep = ''
"let g:airline_right_alt_sep = ''
"let g:airline_symbols.branch = ''
"let g:airline_symbols.readonly = ''
"let g:airline_symbols.linenr = '☰'
"let g:airline_symbols.maxlinenr = ''
"let g:airline_symbols.dirty='⚡'
"
" unicode symbols
"let g:airline_left_sep = '»'
"let g:airline_left_sep = '▶'
"let g:airline_right_sep = '«'
"let g:airline_right_sep = '◀'
"let g:airline_symbols.linenr = '☰'
"let g:airline_symbols.linenr = '␊'
"let g:airline_symbols.linenr = '␤'
"let g:airline_symbols.maxlinenr = ''
"let g:airline_symbols.maxlinenr = '㏑'
"let g:airline_symbols.paste = 'ρ'
"let g:airline_symbols.paste = 'Þ'
"let g:airline_symbols.paste = '∥'
"let g:airline_symbols.spell = 'Ꞩ'
"let g:airline_symbols.notexists = 'Ɇ'

let g:airline_symbols.crypt = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.whitespace = 'Ξ'
"let g:airline_symbols.linenr = '¶'


"
"===================================================================================================
" color scheme
colorscheme PaperColor
set background=light
```

```vim
set nocompatible
let $LANG='en'
set lm=en

set autoread
set encoding=utf-8
"set columns=180
"set lines=45
set go=
set go+=m
set cursorline
"set cursorcolumn
syn on
syntax enable

set ruler
set showcmd
"set wildmenu
"set backspace=indent,eol,start
"set history=20
set hidden

"set laststatus=2
set number
set relativenumber
filetype on
"filetype plugin on
set shiftwidth=2
set softtabstop=2
"set et
set autoindent
set ts=2
set expandtab
"set listchars=eol:?,tab:>
"set listchars=eol:$,tab:>
set listchars=tab:>-
set list

set nobackup       "no backup files
set nowritebackup  "only in case you don't want a backup file while editing
set noswapfile     "no swap files
set undodir=~/.config/nvim/.swap/
set backupdir=~/.config/nvim/.swap/
set directory=~/.config/nvim/.swap/

set hlsearch
set smartcase
set incsearch
set t_Co=256
set ttimeoutlen=50

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
if has("patch-8.1.1564")
  " Recently vim can merge signcolumn and number column into one
  set signcolumn=number
else
  set signcolumn=yes
endif

nmap <F12> :tabnew \|:term<CR>
map <A-q> :q<CR>

"===================================================================================================
call plug#begin('~/.config/nvim/.plug')
"
"Plug 'vim-airline/vim-airline'
"Plug 'vim-airline/vim-airline-themes'
Plug 'itchyny/lightline.vim'
"
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
"
Plug 'rhysd/vim-clang-format'
"
"Plug 'autozimu/LanguageClient-neovim', {'branch': 'next','do': 'bash install.sh'}
"Plug 'prabirshrestha/vim-lsp'
"Plug 'mattn/vim-lsp-settings'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
"
Plug 'tpope/vim-fugitive'
"
Plug 'francoiscabrol/ranger.vim'
Plug 'rbgrouleff/bclose.vim'
"
"Plug 'sainnhe/sonokai'
"Plug 'altercation/vim-colors-solarized'
Plug 'nlknguyen/papercolor-theme'
"
call plug#end()


"===================================================================================================
" airline
"let g:airline_theme='papercolor'
"let g:airline_statusline_ontop = 0
"
"let g:airline_powerline_fonts = 0
"if !exists('g:airline_symbols')
"  let g:airline_symbols={}
"endif
" powerline symbols
"let g:airline_left_sep = ''
"let g:airline_left_alt_sep = ''
"let g:airline_right_sep = ''
"let g:airline_right_alt_sep = ''
"let g:airline_symbols.branch = ''
"let g:airline_symbols.readonly = ''
"let g:airline_symbols.linenr = '☰'
"let g:airline_symbols.maxlinenr = ''
"let g:airline_symbols.dirty='⚡'
"
" unicode symbols
"let g:airline_left_sep = '»'
"let g:airline_left_sep = '▶'
"let g:airline_right_sep = '«'
"let g:airline_right_sep = '◀'
"let g:airline_symbols.linenr = '☰'
"let g:airline_symbols.linenr = '␊'
"let g:airline_symbols.linenr = '␤'
"let g:airline_symbols.maxlinenr = ''
"let g:airline_symbols.maxlinenr = '㏑'
"let g:airline_symbols.paste = 'ρ'
"let g:airline_symbols.paste = 'Þ'
"let g:airline_symbols.paste = '∥'
"let g:airline_symbols.spell = 'Ꞩ'
"let g:airline_symbols.notexists = 'Ɇ'

"let g:airline_symbols.crypt = 'C'
"let g:airline_symbols.readonly = 'R'
"let g:airline_symbols.branch = 'B'
"let g:airline_symbols.whitespace = 'Ξ'
"let g:airline_symbols.linenr = '¶'
"
"
"
"===================================================================================================
" lightline
let g:lightline = {
      \ 'colorscheme': 'PaperColor',
      \ }

let g:lightline = {
      \ 'mode_map': {
      \ 'n' : 'N',
      \ 'i' : 'I',
      \ 'R' : 'R',
      \ 'v' : 'V',
      \ 'V' : 'VL',
      \ "\<C-v>": 'VB',
      \ 'c' : 'C',
      \ 's' : 'S',
      \ 'S' : 'SL',
      \ "\<C-s>": 'SB',
      \ 't': 'T',
      \ },
      \ }
"
"
"===================================================================================================
" search 
nmap <C-p> :Files<CR>
nmap <C-e> :Buffers<CR>
nmap <C-h> :History<CR>
nmap <A-w> :Windows<CR>
" hidden by default, ctrl-/ to toggle
let g:fzf_preview_window = ['right:50%:hidden', 'ctrl-/']
" - down / up / left / right
let g:fzf_layout = { 'down': '40%' }
" [Buffers] Jump to the existing window if possible
let g:fzf_buffers_jump = 1
" Customize fzf colors to match your color scheme
" - fzf#wrap translates this to a set of `--color` options
let g:fzf_colors =
      \ { 'fg':      ['fg', 'Normal'],
      \ 'bg':      ['bg', 'Normal'],
      \ 'hl':      ['fg', 'Comment'],
      \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
      \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
      \ 'hl+':     ['fg', 'Statement'],
      \ 'info':    ['fg', 'PreProc'],
      \ 'border':  ['fg', 'Ignore'],
      \ 'prompt':  ['fg', 'Conditional'],
      \ 'pointer': ['fg', 'Exception'],
      \ 'marker':  ['fg', 'Keyword'],
      \ 'spinner': ['fg', 'Label'],
      \ 'header':  ['fg', 'Comment'] }
"
" Enable per-command history
" - History files will be stored in the specified directory
" - When set, CTRL-N and CTRL-P will be bound to 'next-history' and
"   'previous-history' instead of 'down' and 'up'.
let g:fzf_history_dir = '~/.local/share/fzf-history'
"
"
"===================================================================================================
" clang-format
let g:clang_format#style_options = {
      \ "AccessModifierOffset" : -2,
      \ "AllowShortIfStatementsOnASingleLine" : "false",
      \ "AlwaysBreakTemplateDeclarations" : "true",
      \ "Standard" : "C++11"}
"autocmd FileType c,cpp,objc nnoremap <buffer><Leader>cf :<C-u>ClangFormat<CR>
"autocmd FileType c,cpp,objc vnoremap <buffer><Leader>cf :ClangFormat<CR>
"autocmd FileType c,cpp,objc map <buffer><Leader>x <Plug>(operator-clang-format)
"nmap <Leader>C :ClangFormatAutoToggle<CR>
"nnoremap <silent> == :ClangFormat<CR>
"
"
"===================================================================================================
" LSP
"---------------------------------------------------------------------------------------------------
" language-client-neovim
"set runtimepath+=~/.vim/.plug/LanguageClient-neovim
"let g:LanguageClient_loadSettings = 1
"let g:LanguageClient_diagnosticsEnable = 1
"let g:LanguageClient_settingsPath = expand('~/.vim/languageclient.json')
"let g:LanguageClient_selectionUI = 'quickfix'
"let g:LanguageClient_diagnosticsList = v:null
""let g:LanguageClient_hoverPreview = 'Never'
"let g:LanguageClient_serverCommands = {
"    \ 'cpp': ['/usr/bin/clangd'],
"    \ 'c': ['/usr/bin/clangd'],
"    \ }
"
"nnoremap <silent> K :<Plug>(lcn-hover)<CR>
"nnoremap <silent> gd :<Plug>(lcn-definition)<CR>
"nnoremap <silent> <F2> :<Plug>(lcn-rename)<CR>
"
"
"
"
"
"
"---------------------------------------------------------------------------------------------------
" vim-lsp
"let g:lsp_diagnostics_echo_cursor = 1 " enable echo under cursor when in normal mode
"let g:lsp_highlights_enabled = 1
"let g:lsp_textprop_enabled = 1
"let g:lsp_highlight_references_enabled = 1
"let g:lsp_signs_enabled = 1         " enable signs
"let g:lsp_signs_error = {'text': '✗'}
"
"if executable('clangd')
"    augroup lsp_clangd
"        autocmd!
"        autocmd User lsp_setup call lsp#register_server({
"                    \ 'name': 'clangd',
"                    \ 'cmd': {server_info->['clangd']},
"                    \ 'allowlist': ['c', 'cpp', 'objc', 'objcpp','cc'],
"                    \ })
"        autocmd FileType c setlocal omnifunc=lsp#complete
"        autocmd FileType cpp setlocal omnifunc=lsp#complete
"        autocmd FileType objc setlocal omnifunc=lsp#complete
"        autocmd FileType objcpp setlocal omnifunc=lsp#complete
"    augroup end
"endif
"
"
"---------------------------------------------------------------------------------------------------
" coc-nvim
" GoTo code navigation.
nmap <silent> <C-]> <Plug>(coc-definition)
"nmap <silent> gd <Plug>(coc-definition)
"nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> <C-[> <Plug>(coc-implementation)
nmap <silent> <space>r <Plug>(coc-references)
nmap <silent> <A-o> :CocCommand clangd.switchSourceHeader<CR>
" Use K to show documentation in preview window.
nmap <silent> K :call <SID>show_documentation()<CR>
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction
" Formatting selected code.
"xmap <leader>f <Plug>(coc-format-selected)
"nmap <leader>f <Plug>(coc-format-selected)
" Mappings for CoCList
" Show all diagnostics.
nnoremap <silent><nowait> <space>a  :<C-u>CocLst diagnostics<cr>
" Manage extensions.
"nnoremap <silent><nowait> <space>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
"nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
"nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
"nnoremap <silent><nowait> <space>p  :<C-u>CocListResume<CR>
nnoremap <nowait> <C-f> :CocSearch 
"
"
"==================================================================================================
" git
nnoremap <nowait> <A-g> :G 
"
"
"===================================================================================================
" color scheme
colorscheme PaperColor
set background=dark
"
"
"===================================================================================================
" ranger
" color scheme
" ranger for vim
let g:ranger_map_keys = 0
"open ranger when vim open a directory
let g:ranger_replace_netrw = 1 
"map <A-f> :tabnew \|:Ranger<CR>
"
"
"
```

```vim
set nocompatible
let $LANG='en'
set lm=en

set autoread
set encoding=utf-8
"set columns=180
"set lines=45
set go=
set go+=m
set cursorline
"set cursorcolumn
syn on
syntax enable

set ruler
set showcmd
"set wildmenu
"set backspace=indent,eol,start
"set history=20
set hidden

"set laststatus=2
set number
set relativenumber
filetype on
"filetype plugin on
set shiftwidth=2
set softtabstop=2
"set et
set autoindent
set ts=2
set expandtab
"set listchars=eol:?,tab:>
"set listchars=eol:$,tab:>
set listchars=tab:>-
set list

set nobackup       "no backup files
set nowritebackup  "only in case you don't want a backup file while editing
set noswapfile     "no swap files
set undodir=~/.config/nvim/.swap/
set backupdir=~/.config/nvim/.swap/
set directory=~/.config/nvim/.swap/

set hlsearch
set smartcase
set incsearch
set t_Co=256
set ttimeoutlen=50

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
if has("patch-8.1.1564")
  " Recently vim can merge signcolumn and number column into one
  set signcolumn=number
else
  set signcolumn=yes
endif

nmap <F12> :tabnew \|:term<CR>
map <A-q> :q<CR>

"===================================================================================================
call plug#begin('~/.config/nvim/.plug')
"
"Plug 'vim-airline/vim-airline'
"Plug 'vim-airline/vim-airline-themes'
Plug 'itchyny/lightline.vim'
"
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
"
Plug 'rhysd/vim-clang-format'
"
"Plug 'autozimu/LanguageClient-neovim', {'branch': 'next','do': 'bash install.sh'}
"Plug 'prabirshrestha/vim-lsp'
"Plug 'mattn/vim-lsp-settings'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
"
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
"
Plug 'francoiscabrol/ranger.vim'
Plug 'rbgrouleff/bclose.vim'
"
"Plug 'sainnhe/sonokai'
Plug 'altercation/vim-colors-solarized'
Plug 'nlknguyen/papercolor-theme'
Plug 'rakr/vim-one'
"
call plug#end()


"===================================================================================================
" airline
"let g:airline_theme='papercolor'
"let g:airline_statusline_ontop = 0
"
"let g:airline_powerline_fonts = 0
"if !exists('g:airline_symbols')
"  let g:airline_symbols={}
"endif
" powerline symbols
"let g:airline_left_sep = ''
"let g:airline_left_alt_sep = ''
"let g:airline_right_sep = ''
"let g:airline_right_alt_sep = ''
"let g:airline_symbols.branch = ''
"let g:airline_symbols.readonly = ''
"let g:airline_symbols.linenr = '☰'
"let g:airline_symbols.maxlinenr = ''
"let g:airline_symbols.dirty='⚡'
"
" unicode symbols
"let g:airline_left_sep = '»'
"let g:airline_left_sep = '▶'
"let g:airline_right_sep = '«'
"let g:airline_right_sep = '◀'
"let g:airline_symbols.linenr = '☰'
"let g:airline_symbols.linenr = '␊'
"let g:airline_symbols.linenr = '␤'
"let g:airline_symbols.maxlinenr = ''
"let g:airline_symbols.maxlinenr = '㏑'
"let g:airline_symbols.paste = 'ρ'
"let g:airline_symbols.paste = 'Þ'
"let g:airline_symbols.paste = '∥'
"let g:airline_symbols.spell = 'Ꞩ'
"let g:airline_symbols.notexists = 'Ɇ'

"let g:airline_symbols.crypt = 'C'
"let g:airline_symbols.readonly = 'R'
"let g:airline_symbols.branch = 'B'
"let g:airline_symbols.whitespace = 'Ξ'
"let g:airline_symbols.linenr = '¶'
"
"
"
"===================================================================================================
" lightline
let g:lightline = {
      \ 'colorscheme': 'PaperColor',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead'
      \ },
      \ 'mode_map': {
      \ 'n' : 'N',
      \ 'i' : 'I',
      \ 'R' : 'R',
      \ 'v' : 'V',
      \ 'V' : 'VL',
      \ "\<C-v>": 'VB',
      \ 'c' : 'C',
      \ 's' : 'S',
      \ 'S' : 'SL',
      \ "\<C-s>": 'SB',
      \ 't': 'T',
      \ },
      \ }
"
"
"===================================================================================================
" search 
nmap <C-p> :Files<CR>
nmap <C-e> :Buffers<CR>
nmap <C-h> :History<CR>
nmap <A-w> :Windows<CR>
" hidden by default, ctrl-/ to toggle
let g:fzf_preview_window = ['right:50%:hidden', 'ctrl-/']
" - down / up / left / right
let g:fzf_layout = { 'down': '40%' }
" [Buffers] Jump to the existing window if possible
let g:fzf_buffers_jump = 1
" Customize fzf colors to match your color scheme
" - fzf#wrap translates this to a set of `--color` options
let g:fzf_colors =
      \ { 'fg':      ['fg', 'Normal'],
      \ 'bg':      ['bg', 'Normal'],
      \ 'hl':      ['fg', 'Comment'],
      \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
      \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
      \ 'hl+':     ['fg', 'Statement'],
      \ 'info':    ['fg', 'PreProc'],
      \ 'border':  ['fg', 'Ignore'],
      \ 'prompt':  ['fg', 'Conditional'],
      \ 'pointer': ['fg', 'Exception'],
      \ 'marker':  ['fg', 'Keyword'],
      \ 'spinner': ['fg', 'Label'],
      \ 'header':  ['fg', 'Comment'] }
"
" Enable per-command history
" - History files will be stored in the specified directory
" - When set, CTRL-N and CTRL-P will be bound to 'next-history' and
"   'previous-history' instead of 'down' and 'up'.
let g:fzf_history_dir = '~/.local/share/fzf-history'
"
"
"===================================================================================================
" clang-format
let g:clang_format#style_options = {
      \ "AccessModifierOffset" : -2,
      \ "AllowShortIfStatementsOnASingleLine" : "false",
      \ "AlwaysBreakTemplateDeclarations" : "true",
      \ "Standard" : "C++11"}
"autocmd FileType c,cpp,objc nnoremap <buffer><Leader>cf :<C-u>ClangFormat<CR>
"autocmd FileType c,cpp,objc vnoremap <buffer><Leader>cf :ClangFormat<CR>
"autocmd FileType c,cpp,objc map <buffer><Leader>x <Plug>(operator-clang-format)
"nmap <Leader>C :ClangFormatAutoToggle<CR>
"nnoremap <silent> == :ClangFormat<CR>
"
"
"===================================================================================================
" LSP
"---------------------------------------------------------------------------------------------------
" language-client-neovim
"set runtimepath+=~/.vim/.plug/LanguageClient-neovim
"let g:LanguageClient_loadSettings = 1
"let g:LanguageClient_diagnosticsEnable = 1
"let g:LanguageClient_settingsPath = expand('~/.vim/languageclient.json')
"let g:LanguageClient_selectionUI = 'quickfix'
"let g:LanguageClient_diagnosticsList = v:null
""let g:LanguageClient_hoverPreview = 'Never'
"let g:LanguageClient_serverCommands = {
"    \ 'cpp': ['/usr/bin/clangd'],
"    \ 'c': ['/usr/bin/clangd'],
"    \ }
"
"nnoremap <silent> K :<Plug>(lcn-hover)<CR>
"nnoremap <silent> gd :<Plug>(lcn-definition)<CR>
"nnoremap <silent> <F2> :<Plug>(lcn-rename)<CR>
"
"
"
"
"
"
"---------------------------------------------------------------------------------------------------
" vim-lsp
"let g:lsp_diagnostics_echo_cursor = 1 " enable echo under cursor when in normal mode
"let g:lsp_highlights_enabled = 1
"let g:lsp_textprop_enabled = 1
"let g:lsp_highlight_references_enabled = 1
"let g:lsp_signs_enabled = 1         " enable signs
"let g:lsp_signs_error = {'text': '✗'}
"
"if executable('clangd')
"    augroup lsp_clangd
"        autocmd!
"        autocmd User lsp_setup call lsp#register_server({
"                    \ 'name': 'clangd',
"                    \ 'cmd': {server_info->['clangd']},
"                    \ 'allowlist': ['c', 'cpp', 'objc', 'objcpp','cc'],
"                    \ })
"        autocmd FileType c setlocal omnifunc=lsp#complete
"        autocmd FileType cpp setlocal omnifunc=lsp#complete
"        autocmd FileType objc setlocal omnifunc=lsp#complete
"        autocmd FileType objcpp setlocal omnifunc=lsp#complete
"    augroup end
"endif
"
"
"---------------------------------------------------------------------------------------------------
" coc-nvim
" GoTo code navigation.
nmap <silent> <C-]> <Plug>(coc-definition)
"nmap <silent> gd <Plug>(coc-definition)
"nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> <C-[> <Plug>(coc-implementation)
nmap <silent> <space>r <Plug>(coc-references)
nmap <silent> <A-o> :CocCommand clangd.switchSourceHeader<CR>
" Use K to show documentation in preview window.
nmap <silent> K :call <SID>show_documentation()<CR>
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction
" Formatting selected code.
"xmap <leader>f <Plug>(coc-format-selected)
"nmap <leader>f <Plug>(coc-format-selected)
" Mappings for CoCList
" Show all diagnostics.
nnoremap <silent><nowait> <space>a  :<C-u>CocLst diagnostics<cr>
" Manage extensions.
"nnoremap <silent><nowait> <space>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
"nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
"nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
"nnoremap <silent><nowait> <space>p  :<C-u>CocListResume<CR>
nnoremap <nowait> <C-f> :CocSearch 
"
"
"==================================================================================================
" git
nnoremap <nowait> <A-g> :G 
"
"
"===================================================================================================
" color scheme
colorscheme PaperColor
set background=dark
"
"
"===================================================================================================
" ranger
" color scheme
" ranger for vim
let g:ranger_map_keys = 0
"open ranger when vim open a directory
let g:ranger_replace_netrw = 1 
"map <A-f> :tabnew \|:Ranger<CR>
"
"
```